// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6zH1MMxPJWjSDUjte-D5o86ChLywVMqs',
    appId: '1:17791082107:web:c8ffc297bb73fa991d8cde',
    messagingSenderId: '17791082107',
    projectId: 'bookshifter-5cd45',
    authDomain: 'bookshifter-5cd45.firebaseapp.com',
    storageBucket: 'bookshifter-5cd45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUY5BO0AxdKrGyYI1EJQskXrCdnn8d2BU',
    appId: '1:17791082107:android:acabe5df21530f641d8cde',
    messagingSenderId: '17791082107',
    projectId: 'bookshifter-5cd45',
    storageBucket: 'bookshifter-5cd45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBavz1D5vPhn5MNO9rbgo6js74Cd5bogao',
    appId: '1:17791082107:ios:57117f8524d4aa341d8cde',
    messagingSenderId: '17791082107',
    projectId: 'bookshifter-5cd45',
    storageBucket: 'bookshifter-5cd45.appspot.com',
    iosBundleId: 'com.example.bookshifter',
  );

}